{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.zxing",
    "module": "zxing",
    "version": "1.0-20221213",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "zxing-1.0-20221213.aar",
          "url": "zxing-1.0-20221213.aar",
          "size": 61415,
          "sha512": "55476763926c79f40d90854323125c64db1ad49f34448421573a874d0c130197904f835ae08512f7bd92b47f81793f79f9b46b4512b75dcf0d97c21eb2de8acb",
          "sha256": "705b90d1ac50a93dbd916d755b62ef2b3815674b3a4c0cc8d2deb498e2e92345",
          "sha1": "7601f27fb87601355b9a9f059c7d70b9c7ce0ae6",
          "md5": "8361fc54b4ffe855011b3525606a5caa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "zxing-1.0-20221213.aar",
          "url": "zxing-1.0-20221213.aar",
          "size": 61415,
          "sha512": "55476763926c79f40d90854323125c64db1ad49f34448421573a874d0c130197904f835ae08512f7bd92b47f81793f79f9b46b4512b75dcf0d97c21eb2de8acb",
          "sha256": "705b90d1ac50a93dbd916d755b62ef2b3815674b3a4c0cc8d2deb498e2e92345",
          "sha1": "7601f27fb87601355b9a9f059c7d70b9c7ce0ae6",
          "md5": "8361fc54b4ffe855011b3525606a5caa"
        }
      ]
    }
  ]
}
