{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.filepicker",
    "module": "filepicker",
    "version": "1.0-20230411",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filepicker-1.0-20230411.aar",
          "url": "filepicker-1.0-20230411.aar",
          "size": 43623,
          "sha512": "0243856cc75d95c9fa555621bdb7907e79c180fa6b423ed8cae6c87916a97da35b97e1f47bf021ff1a261dc65afa48ccdf8b8f5af2a43e785848d70d6005e099",
          "sha256": "367bce48250c6a270e06210a9fe1d6b0b0ce08ab10d36117d7e62617dfd184c3",
          "sha1": "a9b03e3bec35c7c904fa23a95c8f5f01afed924d",
          "md5": "9ebc6e3e8ef43daaa99e0647a0cba410"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filepicker-1.0-20230411.aar",
          "url": "filepicker-1.0-20230411.aar",
          "size": 43623,
          "sha512": "0243856cc75d95c9fa555621bdb7907e79c180fa6b423ed8cae6c87916a97da35b97e1f47bf021ff1a261dc65afa48ccdf8b8f5af2a43e785848d70d6005e099",
          "sha256": "367bce48250c6a270e06210a9fe1d6b0b0ce08ab10d36117d7e62617dfd184c3",
          "sha1": "a9b03e3bec35c7c904fa23a95c8f5f01afed924d",
          "md5": "9ebc6e3e8ef43daaa99e0647a0cba410"
        }
      ]
    }
  ]
}
