{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.netlib",
    "module": "netlib",
    "version": "1.0-20220712",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "netlib-1.0-20220712.aar",
          "url": "netlib-1.0-20220712.aar",
          "size": 43955,
          "sha512": "d7ba911266d8582c7a4e73f840444ee1e0f7c24222f5011e4ee7993784dd517767633010abb0cad3cc417fed674702f6ae542340d731cf508297da3b229b2045",
          "sha256": "20091751b08abd003feccaf99b35d91aad876e6a62080dd9f7b315f4c3b4f572",
          "sha1": "44b3c4ffcd6c58e6f1ace22ab0765902864c9d06",
          "md5": "7f9737b182c67d030a83b52380702ca3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-1.0-20220712.aar",
          "url": "netlib-1.0-20220712.aar",
          "size": 43955,
          "sha512": "d7ba911266d8582c7a4e73f840444ee1e0f7c24222f5011e4ee7993784dd517767633010abb0cad3cc417fed674702f6ae542340d731cf508297da3b229b2045",
          "sha256": "20091751b08abd003feccaf99b35d91aad876e6a62080dd9f7b315f4c3b4f572",
          "sha1": "44b3c4ffcd6c58e6f1ace22ab0765902864c9d06",
          "md5": "7f9737b182c67d030a83b52380702ca3"
        }
      ]
    }
  ]
}
