{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.base",
    "module": "base",
    "version": "1.0-20250701",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0-20250701.aar",
          "url": "base-1.0-20250701.aar",
          "size": 16419,
          "sha512": "5b4f74d4cfb7fa7187d360ee63bd83be1173b1b948629c3017a4642ff6ea501e1e566a282af5abd76ec7dfda715e87f04bff27343a27704be6486534e565ea20",
          "sha256": "75ce7309d1c2f35929021f6907f0718e6015f40ace36f296eb85cb70f55e2942",
          "sha1": "47051221ffca2d83669cd67844f259eefd8a5f6a",
          "md5": "41d5e0b999d4b3bdebe78c60f14ce996"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0-20250701.aar",
          "url": "base-1.0-20250701.aar",
          "size": 16419,
          "sha512": "5b4f74d4cfb7fa7187d360ee63bd83be1173b1b948629c3017a4642ff6ea501e1e566a282af5abd76ec7dfda715e87f04bff27343a27704be6486534e565ea20",
          "sha256": "75ce7309d1c2f35929021f6907f0718e6015f40ace36f296eb85cb70f55e2942",
          "sha1": "47051221ffca2d83669cd67844f259eefd8a5f6a",
          "md5": "41d5e0b999d4b3bdebe78c60f14ce996"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "base-1.0-20250701-sources.jar",
          "url": "base-1.0-20250701-sources.jar",
          "size": 12751,
          "sha512": "23c4298246a0a785f40849ca244de3c726b2642e5e1aac05e73a6339a70d70c5f0949b1ed3df2082fe8774301b511dcbe3c1094b7c904a6026ff020618c6bc6c",
          "sha256": "a67495b4446457b7980de6274c1953c101bfd95de3a60103c9c7e76f618e3a2b",
          "sha1": "808dd7b109b303818674834f54b5eddca41617ce",
          "md5": "5e46f8d13b3280702b938957e2252bde"
        }
      ]
    }
  ]
}
