{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20230228",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230228.aar",
          "url": "ota-1.0-20230228.aar",
          "size": 88076,
          "sha512": "b7399b6681ba6e1cc4fbd046b47fc3daa95c82a13207e66f14081846199a650808dc84e51d14a3e390ee84f339b7084176380188aca5fe4c034f846b0b0724b7",
          "sha256": "1dcc8597e8977bfbe24ea12607d708393c0ddc4883e8002775bbdcdf060b6593",
          "sha1": "56e02a147066dff7d183f52ace87e2217e9fc92d",
          "md5": "2da7b2f65f10e1c93ffd1459cabf27a4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "1.0-20230227"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230228.aar",
          "url": "ota-1.0-20230228.aar",
          "size": 88076,
          "sha512": "b7399b6681ba6e1cc4fbd046b47fc3daa95c82a13207e66f14081846199a650808dc84e51d14a3e390ee84f339b7084176380188aca5fe4c034f846b0b0724b7",
          "sha256": "1dcc8597e8977bfbe24ea12607d708393c0ddc4883e8002775bbdcdf060b6593",
          "sha1": "56e02a147066dff7d183f52ace87e2217e9fc92d",
          "md5": "2da7b2f65f10e1c93ffd1459cabf27a4"
        }
      ]
    }
  ]
}
