{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.okpermission",
    "module": "OKPermission",
    "version": "1.0-20220810",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "OKPermission-1.0-20220810.aar",
          "url": "OKPermission-1.0-20220810.aar",
          "size": 54933,
          "sha512": "5b7618bbb8f8ccfe4cbee596ad3537e0cfcbab3604932dbc625cb0bb0b6e856f769ca4d9db60fbb377614e46e0463907b54e92caae07db800606bc62f6d3aa45",
          "sha256": "2e5cad487e867c94ed17ecb200af0fd9e876803c4a03fff7e37c39feba7e253c",
          "sha1": "cc620399e972e44084d72db3247fef8e7b830db2",
          "md5": "1594eb2fc68276bdd341e019f69c51d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "OKPermission-1.0-20220810.aar",
          "url": "OKPermission-1.0-20220810.aar",
          "size": 54933,
          "sha512": "5b7618bbb8f8ccfe4cbee596ad3537e0cfcbab3604932dbc625cb0bb0b6e856f769ca4d9db60fbb377614e46e0463907b54e92caae07db800606bc62f6d3aa45",
          "sha256": "2e5cad487e867c94ed17ecb200af0fd9e876803c4a03fff7e37c39feba7e253c",
          "sha1": "cc620399e972e44084d72db3247fef8e7b830db2",
          "md5": "1594eb2fc68276bdd341e019f69c51d3"
        }
      ]
    }
  ]
}
