{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.base",
    "module": "base",
    "version": "1.0-20221229",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0-20221229.aar",
          "url": "base-1.0-20221229.aar",
          "size": 15880,
          "sha512": "9fc0d25c383357cbaa4a0465f8e29293a1a2e58d01eb78df56de3971f49ea9129803873481ce5b21780bccbd33f7dfc5ed87728ce2e9de285059e11a6f12f023",
          "sha256": "3ff0235753f0b8ede494791672fdc6b80b143a988543a2293da49deedd9f8ae8",
          "sha1": "d6b19f45461c7e4cef480db4a97844f638a89a60",
          "md5": "7395261724d19e086327752745fc3727"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0-20221229.aar",
          "url": "base-1.0-20221229.aar",
          "size": 15880,
          "sha512": "9fc0d25c383357cbaa4a0465f8e29293a1a2e58d01eb78df56de3971f49ea9129803873481ce5b21780bccbd33f7dfc5ed87728ce2e9de285059e11a6f12f023",
          "sha256": "3ff0235753f0b8ede494791672fdc6b80b143a988543a2293da49deedd9f8ae8",
          "sha1": "d6b19f45461c7e4cef480db4a97844f638a89a60",
          "md5": "7395261724d19e086327752745fc3727"
        }
      ]
    }
  ]
}
