{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.baseui",
    "module": "baseui",
    "version": "1.0-20221219",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "baseui-1.0-20221219.aar",
          "url": "baseui-1.0-20221219.aar",
          "size": 137656,
          "sha512": "2211c04f7f1243a9a9815e052f915c907274751e9a58ca2b837e406cd1eeda964c1168993edda5dc14e2054e3496dfe82dd513cfb714a5530867c82405066b87",
          "sha256": "445e38aaa9d310b73b4a5bc6b33cce87672a35caca82940dbae4fe5a19132fa2",
          "sha1": "11701678ea8663ff00329a4c2e70803b384d7e2b",
          "md5": "c48ae6d7c67b6453799d930df8e56d5e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "baseui-1.0-20221219.aar",
          "url": "baseui-1.0-20221219.aar",
          "size": 137656,
          "sha512": "2211c04f7f1243a9a9815e052f915c907274751e9a58ca2b837e406cd1eeda964c1168993edda5dc14e2054e3496dfe82dd513cfb714a5530867c82405066b87",
          "sha256": "445e38aaa9d310b73b4a5bc6b33cce87672a35caca82940dbae4fe5a19132fa2",
          "sha1": "11701678ea8663ff00329a4c2e70803b384d7e2b",
          "md5": "c48ae6d7c67b6453799d930df8e56d5e"
        }
      ]
    }
  ]
}
