{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20230313",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230313.aar",
          "url": "ota-1.0-20230313.aar",
          "size": 86979,
          "sha512": "dca2ddf88399d7ef3f6d02d1a9d6f2633269ccc57bcf0b9839a2b7ffb30b2d57742b41e4673408b70382ce5a9cd9e484ad1f379e6549c6cce87416e1ad4dfb9e",
          "sha256": "dd516c0afdc726bcd22c90d17085d2b94cbd35c5a7964238111761513e363d17",
          "sha1": "bb53ae49e475b877c7aed2cceb85c6a53bc11fa3",
          "md5": "c343eba1fd9873d5c89288df1e771e0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "1.0-20230227"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230313.aar",
          "url": "ota-1.0-20230313.aar",
          "size": 86979,
          "sha512": "dca2ddf88399d7ef3f6d02d1a9d6f2633269ccc57bcf0b9839a2b7ffb30b2d57742b41e4673408b70382ce5a9cd9e484ad1f379e6549c6cce87416e1ad4dfb9e",
          "sha256": "dd516c0afdc726bcd22c90d17085d2b94cbd35c5a7964238111761513e363d17",
          "sha1": "bb53ae49e475b877c7aed2cceb85c6a53bc11fa3",
          "md5": "c343eba1fd9873d5c89288df1e771e0d"
        }
      ]
    }
  ]
}
