{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20240513",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20240513.aar",
          "url": "ota-1.0-20240513.aar",
          "size": 95577,
          "sha512": "ec7524cfdd2876a746eb8d9b065226a69f180dc81f97f21b10bff6d179a01ae3c03aeb6e75a03989abf2c337b2da8a14cdfa0d7cf55ed64d30dda2a9ba81bd96",
          "sha256": "85ca14d76b2ed852d44a5c93fbc884c47646690389f967a40e72868f642f0df2",
          "sha1": "790b545416caebea081191345bc7f51e826ceab7",
          "md5": "fa5b63ea1cb0c7d9ab2ff4e669d218b7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "2.0-20230322"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20240513.aar",
          "url": "ota-1.0-20240513.aar",
          "size": 95577,
          "sha512": "ec7524cfdd2876a746eb8d9b065226a69f180dc81f97f21b10bff6d179a01ae3c03aeb6e75a03989abf2c337b2da8a14cdfa0d7cf55ed64d30dda2a9ba81bd96",
          "sha256": "85ca14d76b2ed852d44a5c93fbc884c47646690389f967a40e72868f642f0df2",
          "sha1": "790b545416caebea081191345bc7f51e826ceab7",
          "md5": "fa5b63ea1cb0c7d9ab2ff4e669d218b7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ota-1.0-20240513-sources.jar",
          "url": "ota-1.0-20240513-sources.jar",
          "size": 26041,
          "sha512": "fbb6976d2e1db25ee6ca1943307b7f68705aab8a43da6f69833ed9b25cd0736d5ef5523b51eda0344f67db93a6fe4436248cdfb37d770c0c6ccf0f4ac80f0fb3",
          "sha256": "371372d5269ea7b794e2c5c81caa700a7dbd34f191e78d47b32ac3f508f6ed86",
          "sha1": "3992953fbce70415df9948a416ce4eef256a640d",
          "md5": "36797bde5c9e6bf141c16ac3d6dddd0c"
        }
      ]
    }
  ]
}
