{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20240513",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20240513.aar",
          "url": "ota-1.0-20240513.aar",
          "size": 99611,
          "sha512": "2954ced2f1dc336a0fa801f9e2119f335bb7e3dc00e641448c9b20b5d937317df72672daf060759800feb3ea674e40099fc8b99cb0bcdaff27cf367116ab62eb",
          "sha256": "0e7b8221816291c9486f7f3decf84f904f27af658cc94ca22386871979b4f3c7",
          "sha1": "99104db6548353e5f49be2b04f33c67ccce5a131",
          "md5": "79bf9362276439b81a72cc2d58928020"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "2.0-20240513"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20240513.aar",
          "url": "ota-1.0-20240513.aar",
          "size": 99611,
          "sha512": "2954ced2f1dc336a0fa801f9e2119f335bb7e3dc00e641448c9b20b5d937317df72672daf060759800feb3ea674e40099fc8b99cb0bcdaff27cf367116ab62eb",
          "sha256": "0e7b8221816291c9486f7f3decf84f904f27af658cc94ca22386871979b4f3c7",
          "sha1": "99104db6548353e5f49be2b04f33c67ccce5a131",
          "md5": "79bf9362276439b81a72cc2d58928020"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ota-1.0-20240513-sources.jar",
          "url": "ota-1.0-20240513-sources.jar",
          "size": 25803,
          "sha512": "a36aecb33ea9bad0a8bada8f23804c7a9afbaca71c66ccd20a30d7d2d25e53b4c7e81acecf82accea514046f138dc903b1adb1e322f4f18202c95118365288bf",
          "sha256": "2ea6dbfe75537cfe1983bb3bcc410853436eb53c3c49ec5c8e45d68248c38923",
          "sha1": "4fc2da97983fc22ab0be800757ab3a0a5f8e8c0a",
          "md5": "e6aefa3e6fbe8ab7b6b8a6b1a292552a"
        }
      ]
    }
  ]
}
