{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20230221",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230221.aar",
          "url": "ota-1.0-20230221.aar",
          "size": 74470,
          "sha512": "c845b795fbd061d93bb42a6634e68b03dfd47a82f28bc2c0669b9e345caf969966d893c36e0d8764a716d7b69e9b0adf7125ff2c5cbdb5e12aaad7664921b3a9",
          "sha256": "36bdee6952437194ca34bde05835d8e5da710cc23a68ca4134cd2701aa68da35",
          "sha1": "7611724ecc053e8a7587e7a6462de478f6eced3c",
          "md5": "063b855f8feb25e24fd5141d175d741d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "1.0-20230217"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230221.aar",
          "url": "ota-1.0-20230221.aar",
          "size": 74470,
          "sha512": "c845b795fbd061d93bb42a6634e68b03dfd47a82f28bc2c0669b9e345caf969966d893c36e0d8764a716d7b69e9b0adf7125ff2c5cbdb5e12aaad7664921b3a9",
          "sha256": "36bdee6952437194ca34bde05835d8e5da710cc23a68ca4134cd2701aa68da35",
          "sha1": "7611724ecc053e8a7587e7a6462de478f6eced3c",
          "md5": "063b855f8feb25e24fd5141d175d741d"
        }
      ]
    }
  ]
}
