{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20230221",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230221.aar",
          "url": "ota-1.0-20230221.aar",
          "size": 72693,
          "sha512": "b3c4bc8f661ee0d993e6e5fe4bd56aa1b58b4353bddfe27ed93846a39ca8d047b6b55cb78c534e844bbdcba5681b1548dcb94c8a7339700c9a8060255cd65ee3",
          "sha256": "bd0e27f965905683b2228570b83fc27a6651db7a54fe3b0426785b0b460f7a36",
          "sha1": "c0c9d51e33c459ae15c61c18da99fd747fe798dc",
          "md5": "62afd514dec6294535e7420b71822324"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "1.0-20230217"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "com.android.systemlib",
          "module": "systemlib",
          "version": {
            "requires": "1.0-20230217"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230221.aar",
          "url": "ota-1.0-20230221.aar",
          "size": 72693,
          "sha512": "b3c4bc8f661ee0d993e6e5fe4bd56aa1b58b4353bddfe27ed93846a39ca8d047b6b55cb78c534e844bbdcba5681b1548dcb94c8a7339700c9a8060255cd65ee3",
          "sha256": "bd0e27f965905683b2228570b83fc27a6651db7a54fe3b0426785b0b460f7a36",
          "sha1": "c0c9d51e33c459ae15c61c18da99fd747fe798dc",
          "md5": "62afd514dec6294535e7420b71822324"
        }
      ]
    }
  ]
}
