{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.netlib",
    "module": "netlib",
    "version": "2.0-20250723",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-2.0-20250723.aar",
          "url": "netlib-2.0-20250723.aar",
          "size": 40747,
          "sha512": "78dfd40709627bbd134f2716ad8b251bf9c8a6d755f9888cd88f3c7224fd59911f9110fbf8ce2585f327937fdf2b8fb748855d7e1419942fe80584ddde11d829",
          "sha256": "310c5f6fd658fe458d963e3eb86aa2c91c41b28f2d13fc5c901a9b95fbf7c592",
          "sha1": "43f667b8622c7c99d17d854d90f35d0339d0f400",
          "md5": "72bdcbd957428b2438c87cdf6af63778"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-dnsoverhttps",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-2.0-20250723.aar",
          "url": "netlib-2.0-20250723.aar",
          "size": 40747,
          "sha512": "78dfd40709627bbd134f2716ad8b251bf9c8a6d755f9888cd88f3c7224fd59911f9110fbf8ce2585f327937fdf2b8fb748855d7e1419942fe80584ddde11d829",
          "sha256": "310c5f6fd658fe458d963e3eb86aa2c91c41b28f2d13fc5c901a9b95fbf7c592",
          "sha1": "43f667b8622c7c99d17d854d90f35d0339d0f400",
          "md5": "72bdcbd957428b2438c87cdf6af63778"
        }
      ]
    }
  ]
}
