{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20250701",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20250701.aar",
          "url": "ota-1.0-20250701.aar",
          "size": 87448,
          "sha512": "8a99279496444e9f4bb76a9296a88689741af255106efe05fadde838961d7abbac0451428b6092565c15bcdcc81b255de3e3ee4527329fe373bedb14086111a0",
          "sha256": "2da1ed96f42456c846bcbdedbef6836aa27f87d677c01c367f38aa964fea2e41",
          "sha1": "48b5c731e66e51de9dd007db85c43e8dee836a81",
          "md5": "a1f5ae47a8518d5175f2a0f0ee3082f5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "2.0-20250611"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20250701.aar",
          "url": "ota-1.0-20250701.aar",
          "size": 87448,
          "sha512": "8a99279496444e9f4bb76a9296a88689741af255106efe05fadde838961d7abbac0451428b6092565c15bcdcc81b255de3e3ee4527329fe373bedb14086111a0",
          "sha256": "2da1ed96f42456c846bcbdedbef6836aa27f87d677c01c367f38aa964fea2e41",
          "sha1": "48b5c731e66e51de9dd007db85c43e8dee836a81",
          "md5": "a1f5ae47a8518d5175f2a0f0ee3082f5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ota-1.0-20250701-sources.jar",
          "url": "ota-1.0-20250701-sources.jar",
          "size": 25941,
          "sha512": "4dc7b02813dae53c7e310b54376806fb7995e6e72f045a82b53a8e7a45ea47c17c4783e00083957dc8c291110e1d9ea4817254412ff9b38490c5f6872a097c5f",
          "sha256": "5892abc1b0738c3a37da9b9432bddbfcd64443c9e9a463a72db289453460b8e2",
          "sha1": "0c10c2278f540e977d41618e2645036432c08f20",
          "md5": "f753981d8282308afc76931e1aada89d"
        }
      ]
    }
  ]
}
