{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.netlib",
    "module": "netlib",
    "version": "2.0-20240125",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-2.0-20240125.aar",
          "url": "netlib-2.0-20240125.aar",
          "size": 39917,
          "sha512": "cd48b9c8abf63862950ca7bd09d921a63b5b288a9c06271bad3ffaeefcbd95e8d436b61d61d8ddba602d5cda59f29c63202b755aedc7fcb14f8552cf7a3e559f",
          "sha256": "2b9dab363e44e14d1a2ff9c74c907af4b9becff00e9d6bed1b886066d0d610c4",
          "sha1": "df456393adb60832ff9ce5fd6202b294edbc2f6b",
          "md5": "39327dcdb3b4a06e1a36721bb3710b2c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-2.0-20240125.aar",
          "url": "netlib-2.0-20240125.aar",
          "size": 39917,
          "sha512": "cd48b9c8abf63862950ca7bd09d921a63b5b288a9c06271bad3ffaeefcbd95e8d436b61d61d8ddba602d5cda59f29c63202b755aedc7fcb14f8552cf7a3e559f",
          "sha256": "2b9dab363e44e14d1a2ff9c74c907af4b9becff00e9d6bed1b886066d0d610c4",
          "sha1": "df456393adb60832ff9ce5fd6202b294edbc2f6b",
          "md5": "39327dcdb3b4a06e1a36721bb3710b2c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "netlib-2.0-20240125-sources.jar",
          "url": "netlib-2.0-20240125-sources.jar",
          "size": 28311,
          "sha512": "e67ceefe01d9a8a2323217a8494a1bc5ec9de01facea4a6000ef15512a6af937a7cb75e9e01110cb7729399b9d97d0c3ad86c4ca0a2adc359a33dd8223fedf90",
          "sha256": "4c9d65c0cf151c11c7102afd3ebd195d5b26807a55c246e7e7045a121a3fa1da",
          "sha1": "7ae9bec8b3d1dc3d09039bf37ead37bb40f6b7b3",
          "md5": "4249c1e0f1acec17c4f3d06c0f23d1c0"
        }
      ]
    }
  ]
}
