{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.vanserialport",
    "module": "vanserialport",
    "version": "1.0-20220506",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "vanserialport-1.0-20220506.aar",
          "url": "vanserialport-1.0-20220506.aar",
          "size": 105627,
          "sha512": "2e3dc78bb2520bad75131c27c0a79900a6f5b9ffc5ff65f8967931974f62fea604c0be591f9f0b3b815c45f02721d95e2440ff67a377cc43ecfcff33ef5afa8b",
          "sha256": "ba0fd7961d7fc6a4224af7d9d9b1d13c8965180836f3a8b18d0373aad7b90347",
          "sha1": "b74da4c05d09425a83abac5a21f90ed5d29f1dd8",
          "md5": "41e58359a64145ecf62728f72f6c814b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "vanserialport-1.0-20220506.aar",
          "url": "vanserialport-1.0-20220506.aar",
          "size": 105627,
          "sha512": "2e3dc78bb2520bad75131c27c0a79900a6f5b9ffc5ff65f8967931974f62fea604c0be591f9f0b3b815c45f02721d95e2440ff67a377cc43ecfcff33ef5afa8b",
          "sha256": "ba0fd7961d7fc6a4224af7d9d9b1d13c8965180836f3a8b18d0373aad7b90347",
          "sha1": "b74da4c05d09425a83abac5a21f90ed5d29f1dd8",
          "md5": "41e58359a64145ecf62728f72f6c814b"
        }
      ]
    }
  ]
}
