{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.baseui",
    "module": "baseui",
    "version": "1.0-20230315",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "baseui-1.0-20230315.aar",
          "url": "baseui-1.0-20230315.aar",
          "size": 98377,
          "sha512": "4379033d5a21603e0ffef74fdd2db007caff7325157d40909063f40d5056634019fd9ef7323af65a3e9692bc04ad632fef09977078bc0a3c37c05a59b8ed28a4",
          "sha256": "b00bfa3ed44920bba296c4613e18845674ee8cd5fdc04bbd623da5b8a5cf7600",
          "sha1": "1be25a39188753ddc3f05dd3a166e42ab5591350",
          "md5": "6e9aaef10c961c65322f432b59f3217a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "baseui-1.0-20230315.aar",
          "url": "baseui-1.0-20230315.aar",
          "size": 98377,
          "sha512": "4379033d5a21603e0ffef74fdd2db007caff7325157d40909063f40d5056634019fd9ef7323af65a3e9692bc04ad632fef09977078bc0a3c37c05a59b8ed28a4",
          "sha256": "b00bfa3ed44920bba296c4613e18845674ee8cd5fdc04bbd623da5b8a5cf7600",
          "sha1": "1be25a39188753ddc3f05dd3a166e42ab5591350",
          "md5": "6e9aaef10c961c65322f432b59f3217a"
        }
      ]
    }
  ]
}
