{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20230302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230302.aar",
          "url": "ota-1.0-20230302.aar",
          "size": 78888,
          "sha512": "a77dd8aceaf8ad9ea69db8f499eac701c285e67226dc002b28a2b15d60dd75e9e09dd2b8325120468297b8d1767282aa6e968560aac40ccace47557093d58d72",
          "sha256": "e89a77c7663ed5125eb74fa66a88ae20d4315a80f9def94decba0e969dde18d8",
          "sha1": "053ea7555c1e8f7c53d8cc539808dfcb4b9edae1",
          "md5": "460d0139355668c082bc2d4f7484dfc2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "1.0-20230227"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230302.aar",
          "url": "ota-1.0-20230302.aar",
          "size": 78888,
          "sha512": "a77dd8aceaf8ad9ea69db8f499eac701c285e67226dc002b28a2b15d60dd75e9e09dd2b8325120468297b8d1767282aa6e968560aac40ccace47557093d58d72",
          "sha256": "e89a77c7663ed5125eb74fa66a88ae20d4315a80f9def94decba0e969dde18d8",
          "sha1": "053ea7555c1e8f7c53d8cc539808dfcb4b9edae1",
          "md5": "460d0139355668c082bc2d4f7484dfc2"
        }
      ]
    }
  ]
}
