{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.netlib",
    "module": "netlib",
    "version": "1.0-20221118",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "netlib-1.0-20221118.aar",
          "url": "netlib-1.0-20221118.aar",
          "size": 42315,
          "sha512": "cecd2d949064a6b5b31e4e06c599a49b5fe68ea9cd0a9076fd7750beaf25e5a2a17e30c8a8efecb883364b12ce4c064c7fcb223b5920663aa3fb44171c5c003e",
          "sha256": "93bfa5c166c8768564f40f9381902e0854125367f61477db8e0d3b985ee177a7",
          "sha1": "6873e0ef51e7f05a003805daf7f1679c2740d9cd",
          "md5": "c3f44f01d860ac97ced34386bba62ad2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-1.0-20221118.aar",
          "url": "netlib-1.0-20221118.aar",
          "size": 42315,
          "sha512": "cecd2d949064a6b5b31e4e06c599a49b5fe68ea9cd0a9076fd7750beaf25e5a2a17e30c8a8efecb883364b12ce4c064c7fcb223b5920663aa3fb44171c5c003e",
          "sha256": "93bfa5c166c8768564f40f9381902e0854125367f61477db8e0d3b985ee177a7",
          "sha1": "6873e0ef51e7f05a003805daf7f1679c2740d9cd",
          "md5": "c3f44f01d860ac97ced34386bba62ad2"
        }
      ]
    }
  ]
}
