{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20230322",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230322.aar",
          "url": "ota-1.0-20230322.aar",
          "size": 87313,
          "sha512": "c2c1d54c04b0e5a3b73599274e96d8583a1553c5eaf2bc3dac80441d6fda03ebac12c6ef03b1287dfa9395534ed2c6d861c7ab8f3cf011b2988f9c0284809bde",
          "sha256": "5c52afdf834d798f687824f73f54240180aa273153bccb649fcedf5b20652a60",
          "sha1": "53ab1361760d444a670ce72ffc41ae64c71785fe",
          "md5": "ee9eb8ed9deef5528a5acc08a8cf37a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "1.0-20230227"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230322.aar",
          "url": "ota-1.0-20230322.aar",
          "size": 87313,
          "sha512": "c2c1d54c04b0e5a3b73599274e96d8583a1553c5eaf2bc3dac80441d6fda03ebac12c6ef03b1287dfa9395534ed2c6d861c7ab8f3cf011b2988f9c0284809bde",
          "sha256": "5c52afdf834d798f687824f73f54240180aa273153bccb649fcedf5b20652a60",
          "sha1": "53ab1361760d444a670ce72ffc41ae64c71785fe",
          "md5": "ee9eb8ed9deef5528a5acc08a8cf37a2"
        }
      ]
    }
  ]
}
