{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20230417",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230417.aar",
          "url": "ota-1.0-20230417.aar",
          "size": 89125,
          "sha512": "8439af10309daaafc4618e095627f5cf0c72430a27479bd3e637328197e510212aef3fd899247f28ff92b267622aaca99317071d9f09885dc5ffa9e4fa75fa71",
          "sha256": "34d14945c11c6712e2e408ca8c1dd60a26a37ef7a9d514a4e68076da395e1128",
          "sha1": "6cbe13348a5ea70eac4bfddfef3d3ecfe94bdbb6",
          "md5": "21f009e82353940eba86c559057eb079"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "1.0-20230227"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230417.aar",
          "url": "ota-1.0-20230417.aar",
          "size": 89125,
          "sha512": "8439af10309daaafc4618e095627f5cf0c72430a27479bd3e637328197e510212aef3fd899247f28ff92b267622aaca99317071d9f09885dc5ffa9e4fa75fa71",
          "sha256": "34d14945c11c6712e2e408ca8c1dd60a26a37ef7a9d514a4e68076da395e1128",
          "sha1": "6cbe13348a5ea70eac4bfddfef3d3ecfe94bdbb6",
          "md5": "21f009e82353940eba86c559057eb079"
        }
      ]
    }
  ]
}
