{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.baseui",
    "module": "baseui",
    "version": "1.0-20230322",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "baseui-1.0-20230322.aar",
          "url": "baseui-1.0-20230322.aar",
          "size": 98350,
          "sha512": "f58bf98b761a6653f05a630efb84c768fb250255da9b0377fe4823c431ddd785475a36795442c1f52b21d5e19eb2e194364f0a4da6306982561e1b18ce6ea32d",
          "sha256": "03d67f4fcf14a69003da4c241145ea610b0027f4b47b840f360629049441a3a9",
          "sha1": "a71dd0a6dc3036cc8abcb62982ed36cb81ae66fd",
          "md5": "e16a73cfc899d9e1a1f92fc0b4f19c7f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "baseui-1.0-20230322.aar",
          "url": "baseui-1.0-20230322.aar",
          "size": 98350,
          "sha512": "f58bf98b761a6653f05a630efb84c768fb250255da9b0377fe4823c431ddd785475a36795442c1f52b21d5e19eb2e194364f0a4da6306982561e1b18ce6ea32d",
          "sha256": "03d67f4fcf14a69003da4c241145ea610b0027f4b47b840f360629049441a3a9",
          "sha1": "a71dd0a6dc3036cc8abcb62982ed36cb81ae66fd",
          "md5": "e16a73cfc899d9e1a1f92fc0b4f19c7f"
        }
      ]
    }
  ]
}
