{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.vanserialport",
    "module": "vanserialport",
    "version": "1.0-20230721",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "vanserialport-1.0-20230721.aar",
          "url": "vanserialport-1.0-20230721.aar",
          "size": 105052,
          "sha512": "e2793dca809c86a9778bfbe16d355dec799070e3e2d2da9b357c01167b6f7cebb83c1106d8183388866d36e80fec5f7e5d13f77a9020e01884c75872f9340f78",
          "sha256": "6340c666ecd9e5cf4145e3165dee18c377cae7663aa2a32b9716e6e38419f5b9",
          "sha1": "401a96c4c30788655253ca1763b9bfdbba0dc852",
          "md5": "b7eb1165233a976b999dec73fdadbcc7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "vanserialport-1.0-20230721.aar",
          "url": "vanserialport-1.0-20230721.aar",
          "size": 105052,
          "sha512": "e2793dca809c86a9778bfbe16d355dec799070e3e2d2da9b357c01167b6f7cebb83c1106d8183388866d36e80fec5f7e5d13f77a9020e01884c75872f9340f78",
          "sha256": "6340c666ecd9e5cf4145e3165dee18c377cae7663aa2a32b9716e6e38419f5b9",
          "sha1": "401a96c4c30788655253ca1763b9bfdbba0dc852",
          "md5": "b7eb1165233a976b999dec73fdadbcc7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "vanserialport-1.0-20230721-sources.jar",
          "url": "vanserialport-1.0-20230721-sources.jar",
          "size": 5123,
          "sha512": "171f0858d9cd7cde4526ab001a57fd60df3eacd03c4d377a9009f81f75e415c52beb2028d5533ffbf964329b2e6eca2b45cbb3a2e51a1fac0bbb425f53a1d51e",
          "sha256": "f113a2b753db42bb3d5ae210bd864fff1306e7fa4dd4a2fc8f68b9622d383713",
          "sha1": "0600519f98aa8689ef9ba103ca4f385b3ceb8c78",
          "md5": "1d2e8316cf0d3523617f2099c6d08add"
        }
      ]
    }
  ]
}
