{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20230307",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230307.aar",
          "url": "ota-1.0-20230307.aar",
          "size": 82172,
          "sha512": "e561cc45313a79ceda9eff396d795286626c8e5f817600ee7e4a7f4a837d180ae4d84d0786712d4f4a9a241d6675a4cc4281429144246d469b4985af344cb1b5",
          "sha256": "28493547eb114b56c127e358e200b1da13f9c2031c663f1080f6aa2e3d40a17c",
          "sha1": "67522cf9d83c0bf1637704d6850480fa979fc089",
          "md5": "c3df15ca70c7e81a24c57ad2b9609c1f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "1.0-20230227"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230307.aar",
          "url": "ota-1.0-20230307.aar",
          "size": 82172,
          "sha512": "e561cc45313a79ceda9eff396d795286626c8e5f817600ee7e4a7f4a837d180ae4d84d0786712d4f4a9a241d6675a4cc4281429144246d469b4985af344cb1b5",
          "sha256": "28493547eb114b56c127e358e200b1da13f9c2031c663f1080f6aa2e3d40a17c",
          "sha1": "67522cf9d83c0bf1637704d6850480fa979fc089",
          "md5": "c3df15ca70c7e81a24c57ad2b9609c1f"
        }
      ]
    }
  ]
}
