{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ota",
    "module": "ota",
    "version": "1.0-20230307",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230307.aar",
          "url": "ota-1.0-20230307.aar",
          "size": 82147,
          "sha512": "e39746440fada7ae3642371412ff209ba2f8a41a3fc73284e672a154474a004dc47a31e6cb8a4a0f362e7ad3365867669f1219300f9458d8f19cfa0226921727",
          "sha256": "e7fcebb8d27c53a6081e2b9a654e6a21f029f23aa840d883066d2ce13e760f6a",
          "sha1": "80e6bf6fbacb6d37fc7993832291da5a6e717612",
          "md5": "7bae8708a3f4b8018044e28daff14371"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.h4de5ing.netlib",
          "module": "netlib",
          "version": {
            "requires": "1.0-20230227"
          }
        },
        {
          "group": "com.github.h4de5ing.gsoncommon",
          "module": "gsoncommon",
          "version": {
            "requires": "1.0-20211125"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ota-1.0-20230307.aar",
          "url": "ota-1.0-20230307.aar",
          "size": 82147,
          "sha512": "e39746440fada7ae3642371412ff209ba2f8a41a3fc73284e672a154474a004dc47a31e6cb8a4a0f362e7ad3365867669f1219300f9458d8f19cfa0226921727",
          "sha256": "e7fcebb8d27c53a6081e2b9a654e6a21f029f23aa840d883066d2ce13e760f6a",
          "sha1": "80e6bf6fbacb6d37fc7993832291da5a6e717612",
          "md5": "7bae8708a3f4b8018044e28daff14371"
        }
      ]
    }
  ]
}
