{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.ymode",
    "module": "ymode",
    "version": "1.0-20250701",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ymode-1.0-20250701.aar",
          "url": "ymode-1.0-20250701.aar",
          "size": 109425,
          "sha512": "fdd70dfc0b1f8cb6c70aeb1abfbfc639097d8a8c3912ed34d84cc97daddb56a42a7e390852c6fc5ef271d123d5d3bb53e89a93c0568d6b7c1fdb8909bf92f782",
          "sha256": "1fbafe5401975ab90df67d9e3bec557e29deae0b2766acb4b9f7ba2e5e7584d5",
          "sha1": "057e1c98dfbf95b92796cf402900bd78b7970333",
          "md5": "60df8aaed40385ab4693899ae4071337"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ymode-1.0-20250701.aar",
          "url": "ymode-1.0-20250701.aar",
          "size": 109425,
          "sha512": "fdd70dfc0b1f8cb6c70aeb1abfbfc639097d8a8c3912ed34d84cc97daddb56a42a7e390852c6fc5ef271d123d5d3bb53e89a93c0568d6b7c1fdb8909bf92f782",
          "sha256": "1fbafe5401975ab90df67d9e3bec557e29deae0b2766acb4b9f7ba2e5e7584d5",
          "sha1": "057e1c98dfbf95b92796cf402900bd78b7970333",
          "md5": "60df8aaed40385ab4693899ae4071337"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ymode-1.0-20250701-sources.jar",
          "url": "ymode-1.0-20250701-sources.jar",
          "size": 15465,
          "sha512": "b20d15126c20d0f100568876cc30e1d3c1fabc0c61d13ddcacfd0e7e52f7a61183e4518793efc1fd86f02fc67fa2d1d189f63b63c6898cd05ca0cee0e8995445",
          "sha256": "65bb5e58e6a8cf9f6faa69bc29b24c6eab76eb93a0963e8259d7f0b705afa5db",
          "sha1": "6574b85fd4026b57b64c12c8c6ed098ef932fb07",
          "md5": "c4c1c33cd0ef3472819b2cfe06f41fd1"
        }
      ]
    }
  ]
}
