{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.netlib",
    "module": "netlib",
    "version": "2.0-20240513",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-2.0-20240513.aar",
          "url": "netlib-2.0-20240513.aar",
          "size": 42299,
          "sha512": "e63d06112d8421796dce307cf0c375f4ec96946e22e6b8b1f8cab135ac3c1b65b829c64ef861bf5796aff5f279138891ebd74a9b353a5ab63c3a194922121845",
          "sha256": "b494a4ec2540a00461634ce1d9beb6c5635d949a1eae057a8a2e5e6461d1accb",
          "sha1": "e793c33fdc4d579927636cb9d3c4ad976d75974a",
          "md5": "4cbdc4cb461d47aa995024d4cbc0c59a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-2.0-20240513.aar",
          "url": "netlib-2.0-20240513.aar",
          "size": 42299,
          "sha512": "e63d06112d8421796dce307cf0c375f4ec96946e22e6b8b1f8cab135ac3c1b65b829c64ef861bf5796aff5f279138891ebd74a9b353a5ab63c3a194922121845",
          "sha256": "b494a4ec2540a00461634ce1d9beb6c5635d949a1eae057a8a2e5e6461d1accb",
          "sha1": "e793c33fdc4d579927636cb9d3c4ad976d75974a",
          "md5": "4cbdc4cb461d47aa995024d4cbc0c59a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "netlib-2.0-20240513-sources.jar",
          "url": "netlib-2.0-20240513-sources.jar",
          "size": 23869,
          "sha512": "cad05d58f39d36f2ce08ceda257ce3651d199dafdbe406174a680ba0ca08c3b7079024247116929a3168e12deb86445f2dc511c52a831515526fd93db42b9c7d",
          "sha256": "06cc0983fe354eced2b827701b9a89e0450d334cfd217ee5311ec95e0e1fb24b",
          "sha1": "be5abfad429235c493d242362cb91c0cb5cf499e",
          "md5": "701a5c958f7ed2f506345e3acda9af7f"
        }
      ]
    }
  ]
}
