{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.h4de5ing.netlib",
    "module": "netlib",
    "version": "2.0-20240513",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-2.0-20240513.aar",
          "url": "netlib-2.0-20240513.aar",
          "size": 45124,
          "sha512": "fe73bf3ede29ab2c718823e1ec11368aaa95695d2b1703233f19245c14ad78bda9cda5a0be6b76967f6e210790119ca8abf032e1bbbfd14d88e73cf7a17f9dda",
          "sha256": "6d635e69ddabe15d228f09a481708d4a92a6b6cf86e87d7a1735888c97b56486",
          "sha1": "f5f143e1f47bb15f17d26dcb58eb4e5bdebb5b98",
          "md5": "92146da9fa835e33fce1891d09d653fc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "netlib-2.0-20240513.aar",
          "url": "netlib-2.0-20240513.aar",
          "size": 45124,
          "sha512": "fe73bf3ede29ab2c718823e1ec11368aaa95695d2b1703233f19245c14ad78bda9cda5a0be6b76967f6e210790119ca8abf032e1bbbfd14d88e73cf7a17f9dda",
          "sha256": "6d635e69ddabe15d228f09a481708d4a92a6b6cf86e87d7a1735888c97b56486",
          "sha1": "f5f143e1f47bb15f17d26dcb58eb4e5bdebb5b98",
          "md5": "92146da9fa835e33fce1891d09d653fc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "netlib-2.0-20240513-sources.jar",
          "url": "netlib-2.0-20240513-sources.jar",
          "size": 23889,
          "sha512": "c8859e494bb5ce57ff2fe61396623342f78a953c98abe351383b2afc8073ad8d0cbe1f9e8242f4e97ee77e70603201e7b8a7ce5a1dd3126381ebaf36f3cfb72d",
          "sha256": "80f0ac60d1dad97a1da7a143386752460659b8221371bdd4093d1609cd1f7c9e",
          "sha1": "21155a1c451a33764ea0c6eaad55cb6745837476",
          "md5": "cd3179a3110adabc0162a92771db30e1"
        }
      ]
    }
  ]
}
